name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a simple test
      run: |
        echo "Running CI workflow"
        echo "Testing repository structure"
        ls -la
        
    - name: Verify HTML files exist
      run: |
        if [ -f "index.html" ]; then
          echo "index.html found"
        else
          echo "index.html not found"
          exit 1
        fi
